"""
Alert Generator
================
Generates human-readable alert content for two audiences:

  1. Officials (DPCC/MCD) -- a structured analysis report: what's
     happening, why, and what to do, backed by the forecast + source
     attribution + enforcement engines already built.
  2. Public -- a short, plain-language civic advisory, mentioning the
     dominant cause and a practical action, in the Hinglish register
     appropriate for a Delhi-NCR-facing public message.

This module only GENERATES content. Actual sending (email/SMS/push) is
handled separately in app/notifications.py, which is optional --
sending requires SMTP credentials that only the user has.
"""

from datetime import datetime


def generate_official_report(point, current_aqi, current_category, forecast_list,
                              attribution, enforcement_entry):
    """Structured analysis report for DPCC/MCD officials."""
    sources = attribution["sources"]
    dominant = max((k for k in sources if k != "background_pct"), key=lambda k: sources[k])
    dominant_label = dominant.replace("_pct", "").replace("_", " ").title()

    forecast_lines = "\n".join(
        f"  +{f['horizon_hours']}h: {round(f['predicted_aqi'])} ({f['predicted_category']})"
        for f in forecast_list
    )

    source_lines = "\n".join(
        f"  {k.replace('_pct', '').replace('_', ' ').title()}: {v}%"
        for k, v in sorted(sources.items(), key=lambda x: -x[1])
    )

    reasons = "\n".join(f"  - {r}" for r in enforcement_entry["reasons"]) if enforcement_entry else "  - N/A"
    actions = "\n".join(f"  - {a}" for a in enforcement_entry["recommended_actions"]) if enforcement_entry else "  - N/A"

    report = f"""URBANAIR AI -- ENFORCEMENT ALERT
Generated: {datetime.now().strftime('%d %b %Y, %I:%M %p')}
Area: {point}

CURRENT STATUS
  AQI: {round(current_aqi)} ({current_category})

FORECAST
{forecast_lines}

SOURCE ATTRIBUTION (dominant: {dominant_label})
{source_lines}

WHY THIS AREA IS FLAGGED
{reasons}

RECOMMENDED ACTIONS
{actions}

---
This is a rule-based analysis (not a black-box prediction) -- every
number above traces back to a documented signal: live traffic
congestion, wind direction/speed, proximity to industrial/construction
zones, and seasonal patterns. Generated by UrbanAir AI.
"""
    return report.strip()


def generate_public_advisory(point, current_aqi, current_category, dominant_source_label):
    """Short, actionable public-facing message. Hinglish register to match
    how Delhi-NCR civic alerts (and the target audience) actually read."""

    action_by_source = {
        "Traffic": "Aaj public transport ya carpool use karne ki koshish karein — traffic hi sabse bada factor hai.",
        "Industrial": "Agar aap is area ke paas rehte hain, khidkiyan band rakhein aur outdoor exposure kam karein.",
        "Construction": "Nearby construction dust ki wajah se, mask pehnein bahar niklte waqt.",
        "Waste Burning": "Stubble/waste burning ka asar hai — sensitive groups ghar ke andar rahein.",
        "Background": "Regional pollution levels high hain — outdoor activity limited rakhein.",
    }
    action = action_by_source.get(dominant_source_label, "Outdoor exposure limited rakhein aaj.")

    severity_note = {
        "Good": "Hawa saaf hai, bahar nikalna safe hai.",
        "Satisfactory": "Hawa theek hai, zyada tar logon ke liye normal din.",
        "Moderate": "Sensitive groups (asthma, elderly, bachche) thoda dhyan rakhein.",
        "Poor": "Prolonged outdoor exertion avoid karein, especially sensitive groups.",
        "Very Poor": "Outdoor activity kam se kam rakhein, N95 mask use karein.",
        "Severe": "Ghar ke andar rahein jitna ho sake, sensitive groups ke liye emergency-level hai.",
    }.get(current_category, "")

    return (
        f"UrbanAir AI Alert -- {point}\n"
        f"AQI abhi: {round(current_aqi)} ({current_category})\n"
        f"{severity_note}\n"
        f"{action}"
    )
